# Basic Prediction Code 

In [2]:
     import numpy as np
X= np.array(([2,9],[1,5],[3,6]), dtype=float)
y= np.array(([92],[86],[89]), dtype=float)
print(X)
print(y)
    #x=X.np.amax(X,axis=0)
    #y=y/100;      #max marks in 100

class Neural_Network(object):
        def __init__(self):
            self.inputsize=2
            self.outputsize=1
            self.hiddensize=3
            self.W1=np.random.rand(self.inputsize,self.hiddensize)
            self.W2=np.random.rand(self.hiddensize,self.outputsize)
            print(self.W1) 
            print(self.W2)
            
        def forward(self,X):
         #forward propagation
            self.z=np.dot(X,self.W1)
            self.z1=self.sigmoid(self.z)
            self.z2=np.dot(self.z1,self.W2)
            o=self.sigmoid(self.z2)
            return o*100    #had to multiply by 100

        def sigmoid(self,s):
            return 1/(1+np.exp(-s))

        
NN=Neural_Network()
o=NN.forward(X)

print("Predicted output\n" +str(o))
print("Actual Output \n" + str(y))

[[2. 9.]
 [1. 5.]
 [3. 6.]]
[[92.]
 [86.]
 [89.]]
[[0.06993189 0.81053904 0.91735321]
 [0.22411612 0.61548841 0.80166258]]
[[0.59520159]
 [0.33653677]
 [0.54714391]]
Predicted output
[[80.4842858 ]
 [79.07417234]
 [79.80316274]]
Actual Output 
[[92.]
 [86.]
 [89.]]
